tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask", "https://github.com/Homebrew/homebrew-cask.git"
tap "homebrew/cask-drivers", "https://github.com/Homebrew/homebrew-cask-drivers.git"
tap "homebrew/cask-fonts", "https://github.com/Homebrew/homebrew-cask-fonts.git"
tap "homebrew/cask-versions"
tap "homebrew/core", "https://github.com/Homebrew/homebrew-core.git"
tap "vitorgalvao/tiny-scripts"
cask "osxfuse"
brew "autopep8"
brew "bash"
brew "bash-completion"
brew "ffmpeg"
brew "flake8"
brew "git"
brew "htop"
brew "iproute2mac"
brew "mas"
brew "mtr"
brew "ntfs-3g"
brew "pipenv"
brew "pylint"
brew "rsync"
brew "ssh-copy-id"
brew "ta-lib"
brew "tox"
brew "twine-pypi"
brew "vim"
brew "wget"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "android-platform-tools"
cask "anydesk"
cask "appcleaner"
cask "caffeine"
cask "ccleaner"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "kodi"
cask "logitech-options"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "omnidisksweeper"
cask "qbittorrent"
cask "qq"
cask "sogouinput"
cask "synergy"
cask "teamviewer"
cask "telegram"
cask "the-unarchiver"
cask "transmission-remote-gui"
cask "v2rayu"
cask "visual-studio-code"
cask "vlc"
cask "wechat"
cask "youdaodict"
mas "Microsoft To Do", id: 1274495053
mas "Xcode", id: 497799835
mas "同花顺", id: 1247341465
